# Generated by Django 5.2 on 2026-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_img',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
